// blog-data.jsx
const BLOG_POSTS = [
  {
    id: 'post-1', slug: 'iyi-emlak-fotografinin-7-kurali',
    title: 'İyi bir emlak fotoğrafının 7 kuralı',
    excerpt: 'Profesyonel emlak fotoğrafçılığında ilanı öne çıkaran şey teknikten önce gözdür. Bu yazıda yıllar içinde geliştirdiğimiz prensipleri paylaşıyoruz.',
    cat: 'Rehber',
    date: '08 Mayıs 2026',
    read: '6 dk okuma',
    cover: 'https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=1600&q=80',
    author: 'Mehmet Aksoy', authorRole: 'Kurucu Fotoğrafçı', authorInit: 'M',
    tags: ['Teknik', 'Kompozisyon', 'Işık'],
    body: [
      ['p', 'Emlak fotoğrafçılığı yalnızca güzel kareler yakalamak değildir. Asıl mesele; potansiyel alıcının ekrandaki görseli "evim olabilir" hissine çevirmektir. Bu hissi yaratan ise teknikten önce kompozisyon, ışık ve sahne hazırlığıdır.'],
      ['h2', '01. Doğru saatte gelin'],
      ['p', 'Mülkün cephesi güneye bakıyorsa öğleden sonra; doğuya bakıyorsa sabah erken çekim yapılmalı. Tepe noktasında güneş, pencerelerden içeri sert ve dağınık ışık atar; sonuç olarak iç mekanlar yanmış görünür.'],
      ['h2', '02. Geniş ama abartısız lens'],
      ['p', '14–24mm aralığı standart. 14mm altına inerseniz duvarlar bükülür, tavan yere paralel olmaz; ilan görseli "balon" gibi görünür. Kullanıcı yanlış orantı algılar ve güveni sarsılır.'],
      ['pull', '"Mülkün gerçek halini abartmadan, en iyi haliyle göstermek; pazarlamanın değil, dürüstlüğün gereğidir."'],
      ['h2', '03. Tripod, hep tripod'],
      ['p', 'Elden çekim ne kadar steady olursanız olun, HDR birleştirmede hizalama hatası yapar. Her oda için aynı sehpa yüksekliği — ortalama 1.20m — ilanın bütünlüğünü sağlar.'],
      ['h2', '04. Sahne hazırlığını mülk sahibine bırakmayın'],
      ['p', 'Oyuncak, çamaşır, eski tencere; hepsini önceden toplayın. Sahip "evim toplu zaten" derken biz 30 kalem fazlalık görürüz. Yumuşak bir hatırlatma ile çekimi 1 saat erteleyip mülkü hazır görmek, sonradan retouch’tan iyidir.'],
      ['h2', '05. HDR — ama görünmez olsun'],
      ['p', 'HDR teknik bir araçtır; estetik bir stil değil. Üç-beş kareyi birleştirip çıkan görsel; insan gözünün gördüğüne yakın olmalı. Renkler patlamamalı, gökyüzü tropikal mavi olmamalı, gölge detayları doğal kalmalı.'],
      ['h2', '06. Pencerelerden bakın'],
      ['p', 'İçeriden çekim yaparken pencere camından dışarı görünen manzara, ilanın hidden gem’ine dönüşür. Boğaz, deniz, park, koru — bunları gösterin. Kapalı perde, yarım fiyat demektir.'],
      ['h2', '07. Mülk değil, yaşam tarzı satın'],
      ['p', 'Son ve en önemli kural: Bir alıcı 60 m² daireyi değil, o dairede oturup kahve içme hayalini satın alır. Kompozisyonunuz bu hayali çağrıştırmalı. Boş kareler yerine; aralanmış perdeyi, masaya bırakılmış bir kitabı, taze çiçeği fotoğraflayın.'],
    ],
  },
  {
    id: 'post-2', slug: 'drone-cekiminde-yasal-cerceve',
    title: 'Drone çekiminde yasal çerçeve: Türkiye için hızlı rehber',
    excerpt: 'SHGM lisansı, uçuş izinleri, yasak bölgeler. Emlak çekimi için drone uçururken bilmeniz gereken her şey.',
    cat: 'Hukuki',
    date: '24 Nisan 2026',
    read: '4 dk okuma',
    cover: 'https://images.unsplash.com/photo-1582407947304-fd86f028f716?w=1600&q=80',
    author: 'Selin Kaya', authorRole: 'Operasyon Direktörü', authorInit: 'S',
    tags: ['Drone', 'SHGM', 'Yasal'],
    body: [
      ['p', 'Drone ile emlak çekimi yapacaksanız önce SHGM kayıt zorunluluğunu yerine getirmeniz şart. 500 gram altı drone’lar bile sicil sistemine kaydedilmek zorunda.'],
      ['h2', 'Lisans gerektiren durumlar'],
      ['p', 'Ticari amaçla — yani müşteri için — uçurulan tüm drone’lar IHA-1 sertifikalı pilot ister. Sertifika SHGM onaylı eğitim merkezlerinden alınır; teorik + pratik sınavla.'],
      ['h2', 'Yasak bölgeler'],
      ['p', 'Havalimanı 9 km yakını, askeri tesisler, cezaevleri, başkanlık binaları ve protokol bölgeleri kesin yasak. Bunlar dışında belediyeden veya ilgili müdürlükten zone bazlı izin gerekebilir.'],
      ['pull', '"Drone’u uçurmadan önce 5 dakikanızı SHGM uygulamasına ayırmak; çekim sonrası 5.000 TL ceza yememenizi sağlar."'],
      ['h2', 'Emlak için pratik öneriler'],
      ['p', 'Site içi mülklerde site yönetiminden yazılı izin alın. Komşu balkonlarına dron yöneltmek "gizliliği ihlal" suçudur — ekstra dikkat. Çekim önce konut sakinine bilgi verilmesi profesyonel etiğin gereğidir.'],
    ],
  },
  {
    id: 'post-3', slug: 'sanal-staging-bos-ev-yuksek-fiyat',
    title: 'Sanal staging: Boş ev, yüksek fiyat',
    excerpt: 'Boş bir mülkün ortalama satış süresi 2.3× daha uzundur. Sanal staging ile dijital olarak döşenmiş ilanlar nasıl çalışır?',
    cat: 'Pazarlama',
    date: '11 Nisan 2026',
    read: '5 dk okuma',
    cover: 'https://images.unsplash.com/photo-1600585154340-be6161a56a0c?w=1600&q=80',
    author: 'Mehmet Aksoy', authorRole: 'Kurucu Fotoğrafçı', authorInit: 'M',
    tags: ['Staging', 'Pazarlama', 'CGI'],
    body: [
      ['p', 'Boş mülk satıldığında alıcı odanın boyutunu yanlış algılar; küçük gibi görünür. Sanal staging — gerçek fotoğraf üzerine 3D mobilya yerleştirme — bu sorunu üç stilde çözüyor.'],
      ['h2', 'Üç farklı stil, tek mülk'],
      ['p', 'Aynı boş salon için modern minimal, klasik ve boho-skandinav versiyonlar üretiyoruz. İlanı farklı kitlelere farklı ilan başlığıyla yayınlamak conversion oranını ortalama 1.8× artırıyor.'],
      ['h2', 'Etik sınır'],
      ['p', 'Sanal staging mevcut yapıyı değiştirmemeli — sadece taşınabilir mobilyaları eklemeli. Duvar yıkmak, balkon kapatmak, manzara değiştirmek aldatıcı pazarlamadır.'],
    ],
  },
  {
    id: 'post-4', slug: '360-sanal-tur-yatirimcilar-icin',
    title: '360° sanal tur: Yurt dışı yatırımcı için yeni standart',
    excerpt: 'İstanbul lüks segmentinde alıcıların %62’si artık ilk ziyareti uzaktan yapıyor. 360° tur teknolojisi neden vazgeçilmez hale geldi?',
    cat: 'Trend',
    date: '02 Nisan 2026',
    read: '7 dk okuma',
    cover: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=1600&q=80',
    author: 'Ayşe Demir', authorRole: 'Lüks Segment Uzmanı', authorInit: 'A',
    tags: ['VR', '360°', 'Lüks'],
    body: [
      ['p', 'Pandemi ile başlayan dijital görüntüleme alışkanlığı, lüks gayrimenkul segmentinde kalıcı standart haline geldi. Körfez ve Avrupa’dan İstanbul’a yatırım yapan alıcıların büyük çoğunluğu mülke fiziken adım atmadan ön karar veriyor.'],
      ['h2', 'Teknoloji'],
      ['p', 'Matterport Pro3 ve Insta360 X4 kullanıyoruz. 200 m² bir daire için ortalama 60 dakika çekim, 24 saat işlem süresi. Çıktı; web tarayıcıda ve VR gözlükte oynatılan adım adım gezinilebilen 3D model.'],
      ['h2', 'Conversion etkisi'],
      ['p', '2025 portföyümüzde 360° tur yayınlanan ilanların ilk 30 günde alınan teklif sayısı, sadece fotoğraf yayınlananlara göre 2.4 kat fazla. Satış kapanış süresi ise ortalama 41 gün → 17 gün.'],
    ],
  },
  {
    id: 'post-5', slug: 'gece-cekimi-isiklar-acik-ev',
    title: 'Gece çekimi: Işıklar açık, ev satılır',
    excerpt: 'Twilight saatte yapılan dış cephe çekimleri, lüks segmentte tıklama oranını ikiye katlıyor. Pratik teknik notlar.',
    cat: 'Teknik',
    date: '18 Mart 2026',
    read: '4 dk okuma',
    cover: 'https://images.unsplash.com/photo-1600585154526-990dced4db0d?w=1600&q=80',
    author: 'Burak Şahin', authorRole: 'Teknik Direktör', authorInit: 'B',
    tags: ['HDR', 'Twilight', 'Cephe'],
    body: [
      ['p', 'Gün batımından 20–35 dakika sonra başlayan "blue hour"; gökyüzünü derin lacivert, ev içlerini sıcak amber yapar. Bu kontrast emlak fotoğrafının en güçlü ifadesidir.'],
      ['h2', 'Pratik checklist'],
      ['p', 'Bir saat önce mülke gelin. Tüm iç mekan ışıklarını açın; bahçe ve havuz aydınlatmasını test edin. ISO 100, f/8, 4–8 saniye pozlamayla 5–7 farklı poz alıp HDR’da birleştirin.'],
    ],
  },
  {
    id: 'post-6', slug: 'mulk-sahibi-icin-cekim-hazirligi',
    title: 'Mülk sahipleri için: Çekim öncesi 24 saat',
    excerpt: 'Çekim günü gelmeden önce yapmanız gereken on adım. Profesyonel sonucu hazırlık belirler.',
    cat: 'Rehber',
    date: '03 Mart 2026',
    read: '5 dk okuma',
    cover: 'https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?w=1600&q=80',
    author: 'Selin Kaya', authorRole: 'Operasyon Direktörü', authorInit: 'S',
    tags: ['Hazırlık', 'Mülk Sahibi'],
    body: [
      ['p', 'Mülkün yatırım değerini görselleyen bir çekim için hazırlık, fotoğrafçı kadar mülk sahibinin de işi.'],
      ['h2', 'Listemiz'],
      ['p', 'Tüm yataklar düzlenmiş, banyo havluları katlanmış, mutfak tezgahı tamamen boş, evcil hayvan eşyaları görünmez konumda olmalı. Yumuşak detaylar — taze çiçek, kitap, bir bardak şarap — sahneye hayat katar ama abartılmamalı.'],
    ],
  },
];

Object.assign(window, { BLOG_POSTS });
